"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Import Path class to work with file and directory paths
from pathlib import Path

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# SECURITY SETTINGS
# ==========================

# Secret key used by Django for cryptographic signing.
# Keep this secret in production.
SECRET_KEY = 'django-insecure-vlz+!@s769x%e7%($r*@r%^o^#u0x&oyhhqshr6-e%w$k_1o=x'

# Enables debugging features.
# Set to False before deploying the project.
DEBUG = True

# Hosts allowed to access the application.
# Empty means only localhost during development.
ALLOWED_HOSTS = []


# ==========================
# INSTALLED APPLICATIONS
# ==========================

INSTALLED_APPS = [

    # Default Django applications
    'django.contrib.admin',          # Admin dashboard
    'django.contrib.auth',           # User authentication
    'django.contrib.contenttypes',   # Content type framework
    'django.contrib.sessions',       # Session management
    'django.contrib.messages',       # Messaging framework
    'django.contrib.staticfiles',    # Static file management

    # Third-party applications
    'rest_framework',                # Django REST Framework for APIs
    'corsheaders',                   # Allows React frontend to communicate with Django

    # Custom application
    'campus',                        # Campus Information & Exploration module
]


# ==========================
# MIDDLEWARE
# ==========================

MIDDLEWARE = [

    # Enables Cross-Origin Resource Sharing (CORS)
    'corsheaders.middleware.CorsMiddleware',

    # Security middleware
    'django.middleware.security.SecurityMiddleware',

    # Session middleware
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Handles common HTTP features
    'django.middleware.common.CommonMiddleware',

    # Protects against Cross Site Request Forgery attacks
    'django.middleware.csrf.CsrfViewMiddleware',

    # Authentication support
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Messaging support
    'django.contrib.messages.middleware.MessageMiddleware',

    # Prevents clickjacking attacks
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Main URL configuration
ROOT_URLCONF = 'core.urls'


# ==========================
# TEMPLATE SETTINGS
# ==========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Additional template directories
        'DIRS': [],

        # Search templates inside installed apps
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                # Adds request object to templates
                'django.template.context_processors.request',

                # Authentication information
                'django.contrib.auth.context_processors.auth',

                # Messages framework
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI application entry point
WSGI_APPLICATION = 'core.wsgi.application'


# ==========================
# DATABASE CONFIGURATION
# ==========================

DATABASES = {
    'default': {

        # MySQL database engine
        'ENGINE': 'django.db.backends.mysql',

        # Database name
        'NAME': 'smartnav',

        # MySQL username
        'USER': 'root',

        # MySQL password
        'PASSWORD': '',

        # Database server
        'HOST': 'localhost',

        # MySQL port
        'PORT': '3306',
    }
}


# ==========================
# PASSWORD VALIDATION
# ==========================

AUTH_PASSWORD_VALIDATORS = [

    # Prevents passwords similar to user information
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    # Minimum password length
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    # Prevents common passwords
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    # Prevents numeric-only passwords
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================
# INTERNATIONALIZATION
# ==========================

# Language of the application
LANGUAGE_CODE = 'en-us'

# Indian timezone
TIME_ZONE = 'Asia/Kolkata'

# Enable Django translation system
USE_I18N = True

# Store datetime values with timezone support
USE_TZ = True


# ==========================
# STATIC FILES
# ==========================

# URL for static files
STATIC_URL = 'static/'

# Directory containing CSS, JavaScript and images
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ==========================
# MEDIA FILES
# ==========================

# URL used for uploaded files
MEDIA_URL = '/media/'

# Folder where uploaded files are stored
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================
# DEFAULT PRIMARY KEY
# ==========================

# Default auto-incrementing primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================
# CORS SETTINGS
# ==========================

# Allow requests from React frontend
CORS_ALLOWED_ORIGINS = [

    # React using Vite
    "http://localhost:5173",

    # React using Create React App
    "http://localhost:3000",
]

# Allow cookies and authentication headers
CORS_ALLOW_CREDENTIALS = True
