export const NAVIGATION_STAGE = {
  OUTDOOR: "OUTDOOR",

  GROUND_FLOOR: "GROUND_FLOOR",

  FIRST_FLOOR: "FIRST_FLOOR",

  SECOND_FLOOR: "SECOND_FLOOR",

  THIRD_FLOOR: "THIRD_FLOOR",

  ARRIVED: "ARRIVED",
};